# Model Define

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, LSTM, Conv1D, Lambda, Input, GlobalAveragePooling1D
from tensorflow.keras.losses import Huber
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

In [2]:
class Custom_Model() :
    def __init__(self, weight, input_shape) :
        self.checkpoint = weight
        self.model = self.build_model(input_shape)
        
    def build_model(self, input_shape : tuple):
        input = Input(shape=input_shape)
        x = LSTM(128, return_sequences=True, activation='tanh', dropout=0.2)(input)
        x = LSTM(64, return_sequences=True, activation='tanh', dropout=0.2)(x)
        x = LSTM(32, return_sequences=True, activation='tanh', dropout=0.2)(x)
        x = GlobalAveragePooling1D()(x)
        output = Dense(1)(x)
        return Model(input, output)
        
    
    def load_model(self) :
        self.model.load_weights(self.checkpoint)
        return self.model


In [3]:
window_size = 6
n_feature = 6

weight = './checkpoints/ckeckpointer.ckpt'
input_shape = (window_size, n_feature)

model = Custom_Model(weight, input_shape)
lstm_model = model.load_model()
lstm_model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 6, 6)]            0         
_________________________________________________________________
lstm (LSTM)                  (None, 6, 128)            69120     
_________________________________________________________________
lstm_1 (LSTM)                (None, 6, 64)             49408     
_________________________________________________________________
lstm_2 (LSTM)                (None, 6, 32)             12416     
_________________________________________________________________
global_average_pooling1d (Gl (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 130,977
Trainable params: 130,977
Non-trainable params: 0
_______________________________________________________

# Inference Data Preprocess

In [7]:
import pandas as pd
import os
from glob import glob
from tqdm import tqdm
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import pyupbit

In [14]:
class Data_preprocess() :
    def __init__(self, ticker, interval, to, count) :
        self.dataset = pyupbit.get_ohlcv(ticker=ticker, interval=interval, to=to, count=count)
        self.preprocess()
        
    def preprocess(self) :
        # index(시간) 제거
        dataset_df = self.dataset.reset_index(drop=True)
        
        # value 제거
        dataset_df = dataset_df.drop(columns=['value'])
        
        # avg_price 추가
        dataset_df['avg_price'] = (dataset_df['high'] + dataset_df['low'] +
                                  dataset_df['open'] + dataset_df['close']) // 4
        
        # min max 정규화 (MinMaxScaler) 적용
        norm = MinMaxScaler()
        norm_dataset = norm.fit_transform(dataset_df)
        norm_dataset = pd.DataFrame(norm_dataset, columns=list(dataset_df.columns))
        self.data = norm_dataset
        
        # 예측될 값(label)인 10분 후 가격
        after10 = np.zeros_like(norm_dataset['close'])
        for i in range(len(norm_dataset['close']) - 1) :
            after10[i] = norm_dataset['close'][i + 1]
            self.label = after10
        
    def windowed_dataset(self, window_size, batch_size) :
        sliced_data = tf.data.Dataset.from_tensor_slices(self.data)
        sliced_data = sliced_data.window(window_size, shift=1, stride=1, drop_remainder=True)
        sliced_data = sliced_data.flat_map(lambda x : x.batch(window_size))
        
        sliced_label = tf.data.Dataset.from_tensor_slices(self.label[window_size:])
        
        sliced_dataset = tf.data.Dataset.zip((sliced_data, sliced_label))
        
        return sliced_dataset.batch(batch_size).prefetch(1)
    
        
        
        

In [16]:
ticker = 'KRW-BTC'
interval ='minute10'
to = f'2021-11-10 00:10'
count = 1000

window_size = 6
batch_size = 1

processed_data =  Data_preprocess(ticker, interval, to, count)
dataset = processed_data.windowed_dataset(window_size, batch_size)


for data in dataset.take(1):
    print("Data == ")
    print(data[0])
    
    print("\nLabel == ")
    print(data[1])

Data == 
tf.Tensor(
[[[0.22419028 0.21817058 0.23657237 0.203964   0.12238874 0.21419267]
  [0.2041498  0.20220437 0.23677737 0.20993023 0.07456903 0.20658573]
  [0.21012146 0.2092089  0.24446494 0.21266053 0.07799429 0.21255145]
  [0.21295547 0.20879687 0.24395244 0.21963798 0.0829506  0.21484395]
  [0.21973684 0.20488257 0.22539975 0.19445849 0.06683506 0.20439744]
  [0.19463563 0.1894314  0.20110701 0.17382951 0.11533618 0.18254051]]], shape=(1, 6, 6), dtype=float64)

Label == 
tf.Tensor([0.16988573], shape=(1,), dtype=float64)


In [17]:
processed_data.label

array([0.20993023, 0.21266053, 0.21963798, 0.19445849, 0.17382951,
       0.17807665, 0.16988573, 0.17039134, 0.16493073, 0.15633532,
       0.15775104, 0.15673981, 0.15259379, 0.15522298, 0.14854889,
       0.14147032, 0.15552634, 0.1782789 , 0.15967236, 0.17595308,
       0.15067246, 0.14167257, 0.12953787, 0.12134695, 0.13469512,
       0.1530994 , 0.1553241 , 0.15077359, 0.13439175, 0.14531297,
       0.14359389, 0.12387501, 0.12104358, 0.13075134, 0.13702093,
       0.13894226, 0.12539185, 0.12377389, 0.10547073, 0.09232481,
       0.09192032, 0.10880777, 0.13044797, 0.1355041 , 0.11426838,
       0.13044797, 0.09101021, 0.10011123, 0.11517848, 0.16189706,
       0.15330165, 0.14602083, 0.16199818, 0.15239155, 0.13631308,
       0.13580746, 0.10809991, 0.11881889, 0.13499848, 0.14197593,
       0.16068359, 0.1720093 , 0.15370614, 0.15026797, 0.15856002,
       0.15684093, 0.14844777, 0.16179593, 0.13975124, 0.1175043 ,
       0.11558297, 0.09910001, 0.09101021, 0.07119021, 0.09505

In [18]:
pred = lstm_model,predict(dataset)
actual = np.asarray(processed_data.label)[6:]

pred = pred[:, 0]

print(pred.shape)

NameError: name 'predict' is not defined